# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - capstone

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
           node-version: "20.15.0"

      - name: Install npm packages
        run: npm install
        working-directory: ./src/main/frontend

      - name: Grant execute permission to react-scripts
        run: chmod +x ./node_modules/.bin/react-scripts
        working-directory: ./src/main/frontend
        

      - name: Build with Gradle
        run: ./gradlew build
    

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: final-0.0.1-SNAPSHOT
          path: '${{ github.workspace }}./build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: final-0.0.1-SNAPSHOT
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_94546099C7044D6D87E7F16153F8628D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2D284AE502BD4E1BB5DB0E404BC9901B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E909E9BB73DD496588C34243BDF5C245 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'capstone'
          slot-name: 'Production'
          package: '*.jar'
          
